name=input("What is your name")
print(f"Hello {name}, I will be telling you a joke today")
input("")
print("Knock, Knock")
input("")
print("Butter")
input("")
print("Butter bring an umbrella, it looks like rain!")
input("")
print("I'm going to tell you one more!")
input("")
print("What do you call a sleeping dinosaur?")
input("")
print("A dino-snore!!!!")
input("")
print("I hope these jokes made you laugh, Bye!!")