print("Welcome")
print("")
name=input("What is your name?")
print(f"Nice to meet you {name}")
print("")
print("We are going to tell a story using your help! I hope you have fun")
animal=input("Pick a animal, any!")
print("")
Name=input("Pick a name for the animal")
print("")
food=input("Pick a food")
print("")
adjective=input("Pick an adjective")
print("")
verb=input("Pick a verb ending in -ING")
print("")
color=input("Pick a color")
print("")
clothing=input("Pick a piece of clothing")
print("")
noun=input("Pick a noun")
print("")
exclamation=input("Pick a exclamation")
print("")
emotion=input("Pick an emotion ending with -ness")
print("")
Emotion=input("Pick another emotion ending in -ed")
print("")
bodypart=input("Pick a Body Part")
print(f"Once upon a time there was a {animal} named {Name}. {Name} loved {adjective} {food} and {verb} around the park.")
print("")
print(f"Today I went to the store to buy {Name} a {color} {clothing}. I tried to but the {clothing} on {Name}'s {bodypart}, I think {Name} liked it")
print("")
print(f"{Name} knocked over a very expensive rack of clothes and broke a {noun}, {exclamation} I screamed! ")
print("")
print(f"The manager fainted with {emotion} and customers ran out of the store looking {Emotion}.")
print("")
print(f"Me and {Name} ran out of the store.. {Name} really is the best pet ever!!")
print("")
print("Thank you for creating this story. Hope you had a fun time!")