print("")
print("")
name=input("What is your name?")
print(f"Nice to meet you {name}")
print("")
print("We are going to tell a story using your help! I hope you have fun")
animal=input("Pick a animal, any!")
print("")
Name=input("Pick a name for the animal")
print("")
food=input("Pick a food")
print("")
adjective=input("Pick an adjective")
print("")
verb=input("Pick a verb ending in -ING")
print("")
color=input("Pick a color")
print("")
clothing=input("Pick a piece of clothing")
print(f"Once upon a time there was a {animal} named {Name}. {Name} loved {adjective} {food} and {verb} around the park.")
print(f"Today I went to the store to buy {Name} a {color} {clothing}.")
